import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import { geniusWebApiURL, spotifyWebApiURL } from '../constants/'
import Router from 'next/router'

export default function Home() {
  const [accessToken, setAccessToken] = useState('');
  const [geniusAccessToken, setGeniusAccessToken] = useState('');


  function handleSpotifyClick() {
    document.location = spotifyWebApiURL
  }

  function setSpotifyToken() {
    let url = window.location.href;
    if (url.indexOf('_token') > -1) {
      setAccessToken(url.split('_token=')[1].split("&")[0].trim())
    }
  }


  function handleGeniusClick() {
    document.location = geniusWebApiURL
  }

  function setGeniusToken() {
    let url = window.location.href;
    if (url.indexOf('_token') > -1) {
      setAccessToken(url.split('_token=')[1].split("&")[0].trim())
    }
  }

  useEffect(() => {
    setSpotifyToken();
    setGeniusAccessToken();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Lyricly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        token: {accessToken}
        <h1 className={styles.title}>
          Lyricly
        </h1>
        <button onClick={() => handleSpotifyClick()}>
          Connect to Spotify
        </button>
        <button onClick={() => handleGeniusClick()}>
          Connect to Genius
        </button>
        <button onClick={event => Router.push({
          pathname: '/app',
          query: { accessToken }
        })}
          className="">
          {accessToken !== '' ? 'Go To Your Current Lyrics' : 'Login'}
        </button>

      </main>

    </div>
  )
}
